# Generated by Django 2.0.13 on 2019-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone1', models.CharField(blank=True, max_length=12)),
                ('phone2', models.CharField(blank=True, max_length=12)),
                ('address1', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('core_member', models.BooleanField()),
                ('outter_core_member', models.BooleanField()),
                ('events_only_member', models.BooleanField()),
            ],
        ),
    ]
