# Generated by Django 2.0.13 on 2019-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190423_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
