# Generated by Django 2.0.13 on 2019-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190423_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone2',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
