# Generated by Django 2.0.13 on 2019-04-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190424_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Core', 'Core Member'), ('Outer Core', 'Outer Core'), ('Events Only', 'Events Only')], max_length=11),
        ),
    ]
