# Generated by Django 2.0.13 on 2019-04-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190424_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
