# Generated by Django 2.0.13 on 2019-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20190424_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Core', 'Core Member'), ('Outer Core', 'Outer Core'), ('Events', 'Events Only')], max_length=11),
        ),
    ]
