# Generated by Django 2.0.13 on 2019-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20190424_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Core', 'Core Member'), ('Outer Core', 'Outer Core Member'), ('Events', 'Events Only Member')], max_length=11),
        ),
    ]
